### ISSUE TITLE
Annotated routes don't show in sitemap

### ISSUE THREAD

**Issue by Mondane** [prestaconcept/PrestaSitemapBundle#101]
In a symfony 2.8 installation, I have the bundle configured as:

config.yml
```
presta_sitemap:
   route_annotation_listener: true
```

routing.yml
```
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

company_dweh:
    resource: "@CompanyDwehBundle/Controller"
    type: annotation

PrestaSitemapBundle:
    resource: "@PrestaSitemapBundle/Resources/config/routing.yml"
    prefix:   /
```

And in my controller:

```
<?php

namespace Company\DwehBundle\Controller;

use APY\BreadcrumbTrailBundle\Annotation\Breadcrumb;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

/**
 * @Route("/")
 * @Breadcrumb("Home", route={"name"="company_dweh_default_index"})
 */
class DefaultController extends Controller
{
    /**
     * @Route("", options={"sitemap" =  true })
     */
    public function indexAction()
    {
        return $this->render('CompanyDwehBundle:Default:index.html.twig', array());
    }
}
```

But, after clearing the cache, the route doesn't appear in the sitemap:

```

<?xml version="1.0" encoding="UTF-8"?>
    <sitemapindex xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.sitemaps.org/schemas/sitemap/0.9 http://www.sitemaps.org/schemas/sitemap/0.9/siteindex.xsd" xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    <sitemap>
        <loc>http://dweh.swdev.company.nl/app_dev.php/sitemap.default.xml</loc>
        <lastmod>2016-04-04T16:00:41+02:00</lastmod>
    </sitemap>
</sitemapindex>
```

I've tried the annotation like this with the same result:

```
<?php

namespace Company\DwehBundle\Controller;

use APY\BreadcrumbTrailBundle\Annotation\Breadcrumb;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

/**
 * @Breadcrumb("Home", route={"name"="company_dweh_default_index"})
 */
class DefaultController extends Controller
{
    /**
     * @Route("/", name="homepage", options={"sitemap" = true})
     */
    public function indexAction()
    {
        return $this->render('CompanyDwehBundle:Default:index.html.twig', array());
    }
}
```

What could I be missing?
