### ISSUE TITLE
RfC: yaml support for static routes

### ISSUE THREAD

**Issue by ninsky** [prestaconcept/PrestaSitemapBundle#103]
Hi

I'm defining routes in yaml files. Would be great if I could add a sitemap=true option to these static  routes to add them automatically to my generated sitemap. 

I'm not sure if this bundle is still maintained. 

BR
ninsky

**Comment by CharlyPoppins** [comment]
+1

**Comment by yann-eugone** [comment]
Hi, this bundle is still maintained, sorry for answering so late.
I used to configure my routes using YAML too, but i have no problem.
Do you encounter some issues ?

**Comment by CharlyPoppins** [comment]
In my case I try to use @Route for static routes and SitemapListenerInterface for my dynamic routes.

Then static routes does not appear in the generated sitemap.

**Comment by yann-eugone** [comment]
I made a try with a routing config file like the following : 

```yml
yml_homepage:
    path:     /
    defaults: { _controller: AppBundle:Default:index }
    options:
        sitemap: true
```

and it works just fine...

**Comment by CharlyPoppins** [comment]
I tried this :
```
site_about:
    path: /qui-sommes-nous
    defaults: { _controller: SiteBundle:Default:About }
    options:
        sitemap: true
```
combine to the SitemapListener :
````
public function populateSitemap(SitemapPopulateEvent $event)
{
	// my loop
$event->getGenerator()->addUrl($urlLang, $localeCourante);
	//
}
```

URL from the routing.yml are not generated neither in sitemap.xml nor sitemap.fr.xml
I've only got URL generated by the SitemapListener

maybe I have to configure something due to multiple locales ? also I'm using JMSI18nRoutingBundle
