### ISSUE TITLE
Use Symfony Cache Component instead of DoctrineCache

### ISSUE THREAD

**Issue by kopeckyales** [prestaconcept/PrestaSitemapBundle#142]
Since Symfony 3.1, Symfony provides cache component out of the box. It would be nice to drop dependency on DoctrineCache and use default symfony cache component for caching sitemaps.

Any plans to implement this?

**Comment by unexge** [comment]
i am using this dirty hack while waiting #160 to merge.

```yaml
# config/packages/presta_sitemap.yaml
services:
    app.presta_sitemap.cache:
        class: Symfony\Component\Cache\DoctrineProvider
        arguments:
            - "@cache.app" # using app cache pool my cause collisions, you can use custom cache pool

    app.presta_sitemap.generator:
        class: Presta\SitemapBundle\Service\Generator
        autowire: true
        arguments:
            - "" # autowired
            - "" # autowired
            - "@app.presta_sitemap.cache"
            - "%presta_sitemap.timetolive%"
            - "%presta_sitemap.items_by_set%"
        calls:
            - method: setDefaults
              arguments:
                - '%presta_sitemap.defaults%'

    # if you want to autowire Generator service
    Presta\SitemapBundle\Service\Generator: '@app.presta_sitemap.generator'

presta_sitemap:
    generator: app.presta_sitemap.generator
    # ...
```
