### ISSUE TITLE
Disable priority

### ISSUE THREAD

**Issue by pesseyjulien** [prestaconcept/PrestaSitemapBundle#229]
Hi,

Great bundle, thanks !

Quick question, is it possible to disable priority ? As Google don't consider it anymore.

Thanks,
Julien

**Comment by yann-eugone** [comment]
Hi Julien ! Thank you for these words. 

Never tried myself, but setting priority to `null` should do it. Did you tried it ?

Maybe globally in the config : 
```yaml
presta_sitemap:
    defaults:
        priority: null
```
https://github.com/prestaconcept/PrestaSitemapBundle/blob/master/Resources/doc/2-configuration.md#changing-the-defaults
