### ISSUE TITLE
Several sitemaps with locales

### ISSUE THREAD

**Issue by zhukovsergei** [prestaconcept/PrestaSitemapBundle#267]
Hi guys!
Can you say please: is it possible to generate with your bundle the next structure:

```
sitemap.xml - contains links to the others siteamps
sitemap.en.xml en articles links
sitemap.de.xml de articles links
sitemap.fr.xml fr articles links

```

How to configure sitemap.{_locale}.xml configuratoion? Thanks!

**Comment by norkunas** [comment]
Hi.
You could implement this using different sections for each locale. For example:

```php
<?php

declare(strict_types=1);

namespace App\EventSubscriber;

use Presta\SitemapBundle\Event\SitemapPopulateEvent;
use Presta\SitemapBundle\Sitemap\Url\UrlConcrete;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use function in_array;

final class AddEnArticlesToSitemap implements EventSubscriberInterface
{
    public function __invoke(SitemapPopulateEvent $event): void
    {
        if (!in_array($event->getSection(), [null, 'en'], true)) {
            return;
        }

        $urlContainer = $event->getUrlContainer();

        $articles = ..retrieve en articles..

        foreach ($articles as $article) {
            $url = new UrlConcrete('https://example.com/en/'.$article['slug']);
            $urlContainer->addUrl($url, 'en');
        }
    }

    public static function getSubscribedEvents(): array
    {
        return [
            SitemapPopulateEvent::ON_SITEMAP_POPULATE => '__invoke',
        ];
    }
}
```

```php
<?php

declare(strict_types=1);

namespace App\EventSubscriber;

use Presta\SitemapBundle\Event\SitemapPopulateEvent;
use Presta\SitemapBundle\Sitemap\Url\UrlConcrete;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use function in_array;

final class AddDeArticlesToSitemap implements EventSubscriberInterface
{
    public function __invoke(SitemapPopulateEvent $event): void
    {
        if (!in_array($event->getSection(), [null, 'de'], true)) {
            return;
        }

        $urlContainer = $event->getUrlContainer();

        $articles = ..retrieve de articles..

        foreach ($articles as $article) {
            $url = new UrlConcrete('https://example.com/de/'.$article['slug']);
            $urlContainer->addUrl($url, 'de');
        }
    }

    public static function getSubscribedEvents(): array
    {
        return [
            SitemapPopulateEvent::ON_SITEMAP_POPULATE => '__invoke',
        ];
    }
}
```

**Comment by zhukovsergei** [comment]
@norkunas Thanks a lot for the answer and example!

But i'm actually stuck with a section. I see only directive 

```
# config/packages/presta_sitemap.yaml
presta_sitemap:
    default_section: default
```
Also I can use it in annotations `"section" = "misc"` and in routes.yaml

But I don't realize how I can declare them.

**Comment by norkunas** [comment]
You don't need to configure the section in `presta_sitemap.yaml`.

Basically you just provide the section when adding url's to the sitemap container.

Then if you directly import the `@PrestaSitemapBundle/Resources/config/routing.yml` it should work ouf the box.

There are two routes from this bundle:
```yaml
PrestaSitemapBundle_index:
    path:     "/%presta_sitemap.sitemap_file_prefix%.{_format}"
    defaults: { _controller: Presta\SitemapBundle\Controller\SitemapController::indexAction }
    requirements:
        _format: xml

PrestaSitemapBundle_section:
    path:     "/%presta_sitemap.sitemap_file_prefix%.{name}.{_format}"
    defaults: { _controller: Presta\SitemapBundle\Controller\SitemapController::sectionAction }
    requirements:
        _format: xml
```

The first one defines the /sitemap.xml which would link to your dumped sections (locales in your context), and the second /sitemap.{section_locale}.xml would be used for the links.
