### ISSUE TITLE
How to include translated routes in  dump file ?

### ISSUE THREAD

**Issue by PicassoHouessou** [prestaconcept/PrestaSitemapBundle#300]
My links look like:
https://127.0.0.1:8000/en/contact
https://127.0.0.1:8000/fr/contact
https://127.0.0.1:8000/de/contact
```yaml
presta_sitemap:
    resource: "@PrestaSitemapBundle/config/routing.yml"
    route_annotation_listener: true
    defaults:
        priority: 1
        changefreq: hourly
        lastmod: now
    alternate:
        enabled: true
        default_locale: "fr"
        locales: ["fr", "en", "de"]
        i18n: symfony

```
When I run  **php bin/console presta:sitemaps:dump** I don't see in the dump file, the translated route.
In the dump file we have only link with my default locale 
How to get the links with all locales?
