### ISSUE TITLE
Help: No URLs were added to sitemap by EventListeners - this may happen when provided section is invalid

### ISSUE THREAD

**Issue by kostt** [prestaconcept/PrestaSitemapBundle#325]
Help please. I need make dumped sitemaps Symfony 6.3

What i do:

composer require presta/sitemap-bundle
"presta/sitemap-bundle": "^3.3"

```
<?php
// config/bundles.php
return [
    //...
    Presta\SitemapBundle\PrestaSitemapBundle::class => ['all' => true],
];

```
```
# config/routes/presta_sitemap.yaml
presta_sitemap:
    resource: "@PrestaSitemapBundle/config/routing.yml"
```
    
```
# config/services.yaml
parameters:
    router.request_context.host:   my-domain.com
    router.request_context.scheme: http
```
    
    
bin/console presta:sitemaps:dump
Output: No URLs were added to sitemap by EventListeners - this may happen when provided section is invalid
