### ISSUE TITLE
Allow a custom generator service

### ISSUE THREAD

**Issue by jvandesande** [prestaconcept/PrestaSitemapBundle#55]
It would be great if I could build my own sitemap generator and use that instead of the default sitemap generator.  Configuration might look like this:

```yaml
# app/config/config.yml
presta_sitemap:
    generator: my_app.sitemap_generator # service id of my sitemap generator
```

To support this, a GeneratorInterface should be created that should be implemented by the generator.
A few reasons for building your own sitemap generator:
* Custom caching implementation
* Reduce memory usage (like the DumperGenerator)
* etc.
